int _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int _sqrt_recursion(int n);
int _check_for_sqrt(int n, int guess);
int is_prime_number(int n);
int check_prime(int n, int guess);
int is_palindrome(char *s);
int check_opp_str(char *s, int a, int b);
int wildcmp(char *s1, char *s2);
